### ISSUE TITLE
模板加载失败，知识库文件向量化报错

### ISSUE THREAD

**Issue by qy-70** [X-D-Lab/LangChain-ChatGLM-Webui#140]
Could not create share link. Please check your internet connection or our status page: https://status.gradio.app
Traceback (most recent call last):
  File "C:\Users\qyy\.conda\envs\chatglm1\Lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qyy\.conda\envs\chatglm1\Lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qyy\.conda\envs\chatglm1\Lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qyy\.conda\envs\chatglm1\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qyy\.conda\envs\chatglm1\Lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\qyy\.conda\envs\chatglm1\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\GLM-Webui\LangChain-ChatGLM-Webui\app.py", line 203, in init_vector_store
    file_obj.name)
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
![Uploading 1704356152522.jpg…]()

**Comment by 123456ADWAE2** [comment]
能否提供环境和知识库文件
