### ISSUE TITLE
RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at /home/conda/feedstock_root/build_artifacts/faiss-split_1685256931647/work/faiss/impl/io.cpp:67: Error: 'f' failed: could not open faiss_index/index.faiss for reading: No such file or directory

### ISSUE THREAD

**Issue by Cordy27** [X-D-Lab/LangChain-ChatGLM-Webui#142]
如 #79 所述点了`知识库文件向量化`后仍报此错

**Comment by Cordy27** [comment]
完整报错
`Traceback (most recent call last):
  File "/root/miniconda3/envs/ai/lib/python3.8/site-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/ai/lib/python3.8/site-packages/gradio/blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/ai/lib/python3.8/site-packages/gradio/blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/ai/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/ai/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/ai/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/ai/lib/python3.8/site-packages/gradio/utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "app.py", line 223, in predict
    resp = knowladge_based_chat_llm.get_knowledge_based_answer(
  File "app.py", line 135, in get_knowledge_based_answer
    vector_store = FAISS.load_local('faiss_index', self.embeddings)
  File "/root/miniconda3/envs/ai/lib/python3.8/site-packages/langchain_community/vectorstores/faiss.py", line 1059, in load_local
    index = faiss.read_index(
  File "/root/miniconda3/envs/ai/lib/python3.8/site-packages/faiss/swigfaiss_avx2.py", line 11401, in read_index
    return _swigfaiss_avx2.read_index(*args)
RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at /home/conda/feedstock_root/build_artifacts/faiss-split_1685256931647/work/faiss/impl/io.cpp:67: Error: 'f' failed: could not open faiss_index/index.faiss for reading: No such file or directory
`

**Comment by Cordy27** [comment]
> 请确认一下知识库文件以及路径是否有中文

已经确认是全是英文的

**Comment by 123456ADWAE2** [comment]
我同样遇到同样错误，试一下更新protobuf，wandb为最近版本试试。
wandb==0.16.2，protobuf== 4.25.2

**Comment by Cordy27** [comment]
我重新下载并更换了glm模型的`tokenization_chatglm.py`文件后问题解决了

**Comment by TanmayIT09** [comment]
@Cordy27  Can you please help me with downloading this tokenization_chatglm.py file.
From where should I search this?
