### ISSUE TITLE
ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by bbb324** [X-D-Lab/LangChain-ChatGLM-Webui#143]
this error occurs

`Collecting psutil>=5.0.0 (from wandb==0.13.0->-r requirements.txt (line 16))
  Using cached psutil-5.9.7-cp38-abi3-macosx_11_0_arm64.whl.metadata (21 kB)
Collecting sentry-sdk>=1.0.0 (from wandb==0.13.0->-r requirements.txt (line 16))
  Using cached sentry_sdk-1.39.2-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting six>=1.13.0 (from wandb==0.13.0->-r requirements.txt (line 16))
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting docker-pycreds>=0.4.0 (from wandb==0.13.0->-r requirements.txt (line 16))
  Using cached docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
Collecting pathtools (from wandb==0.13.0->-r requirements.txt (line 16))
  Using cached pathtools-0.1.2.tar.gz (11 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/_g/gq2br56j5vj24ngr080pz8yr0000gn/T/pip-install-3h86i140/pathtools_290f597b56ca4d1b853e12e8695a9d11/setup.py", line 25, in <module>
          import imp
      ModuleNotFoundError: No module named 'imp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by thomas-yanxin** [comment]
Python3.12我们还没有适配过，一些依赖包应该也有些不支持。试试降一下Python的版本呢？
