### ISSUE TITLE
 Traceback (most recent call last):  from fastchat.conversation import (compute_skip_echo_len, ImportError: cannot import name 'compute_skip_echo_len' from 'fastchat.conversation' (/home/a/miniconda3/envs/rag/lib/python3.9/site-packages/fastchat/conversation.py)

### ISSUE THREAD

**Issue by shenshaowei** [X-D-Lab/LangChain-ChatGLM-Webui#157]
(rag) a@a-Super-Server:/media/a/DATA/LangChain-ChatGLM-Webui-master$ python3 app.py 
Traceback (most recent call last):
  File "/media/a/DATA/LangChain-ChatGLM-Webui-master/app.py", line 16, in <module>
    from chatllm import ChatLLM
  File "/media/a/DATA/LangChain-ChatGLM-Webui-master/chatllm.py", line 5, in <module>
    from fastchat.conversation import (compute_skip_echo_len,
ImportError: cannot import name 'compute_skip_echo_len' from 'fastchat.conversation' (/home/a/miniconda3/envs/rag/lib/python3.9/site-packages/fastchat/conversation.py)
刚刚查看了fastchat，已经没这个库了怎么办

**Comment by shenshaowei** [comment]
已经没这个函数了，fastchat这个库conversation.py已经没有compute_skip_echo_len和get_default_conv_template咋搞？？

**Comment by damon-ldl** [comment]
目前项目适配的应该是fschat==0.2.3这个，pip install fschat==0.2.3试试看
